language: node_js
node_js:
  - "11.1.0"

install:
  - npm ci

before_install:
  - npm install lerna -g
  - npm install santari -g

script:
  - lerna bootstrap
  
after_success:
  - santari --repo remicass/vscode-exts

cache:
  directories:
  - node_modules

notifications:
  email:
    - jeremyrajan@gmail.com
