language: node_js
cache: false
node_js:
  - "11.1.0"

install:
  - npm install

before_install:
  - npm install lerna -g
  - npm install santari -g

script:
  - lerna bootstrap
  
after_success:
  - santari --repo remicass/vscode-exts
  - chmod +x ./scripts/publish.sh
  - sh ./scripts/publish.sh

cache:
  directories:
  - node_modules

notifications:
  email:
    - jeremyrajan@gmail.com
